#!/usr/bin/env bash

set -e

cd /usr/src/linux

if [ ! -f .config ]; then
	zcat /proc/config.gz > .config
	make olddefconfig
fi

threads=$(( $(nproc) * 3 / 4 ))

make -j $threads
make -j $threads modules_install

mount /boot

mv -v /boot/kernel "/boot/kernel_$(date +%Y%m%d)_$(uname -r)"
zcat /proc/config.gz > "/boot/kernel_$(date +%Y%m%d)_$(uname -r).conf"

cp -v arch/x86_64/boot/bzImage /boot/kernel
lilo

umount /boot
