#!/usr/bin/env bash

set -e

cd /usr/src/linux

if [ ! -f .config ]; then
	zcat /proc/config.gz > .config
	make olddefconfig
fi

threads=$(( $(nproc) * 3 / 4 ))

make -j $threads
make -j $threads modules_install

for d in /boot{,/efi}; do
	if grep -qE "^[^#].+\s$d\s" /etc/fstab; then
		mount "$d"
	fi
done

if [ -x /sbin/installkernel ]; then
	make install
else
	mv -v /boot/kernel "/boot/kernel_$(date +%Y%m%d)_$(uname -r)"
	zcat /proc/config.gz > "/boot/kernel_$(date +%Y%m%d)_$(uname -r).conf"

	cp -v arch/x86_64/boot/bzImage /boot/kernel
fi

if command -v grub-install >/dev/null 2>&1; then
	grub-install --efi-directory=/boot/efi
else
	lilo
fi

for d in /boot{/efi,}; do
	if grep -qE "^[^#].+\s$d\s" /etc/fstab; then
		umount "$d"
	fi
done
